services:
  magasin-1:
    image: mysql:lts
    container_name: magasin-1
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: cpnv
      MYSQL_PASSWORD: BigPassword
      MYSQL_ROOT_PASSWORD: BigPassword
    volumes:
      - ./config:/etc/mysql/conf.d
      - magasin-1:/var/lib/mysql

  magasin-2:
    image: mysql:lts
    container_name: magasin-2
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: cpnv
      MYSQL_PASSWORD: BigPassword
      MYSQL_ROOT_PASSWORD: BigPassword
    volumes:
      - ./config:/etc/mysql/conf.d
      - magasin-2:/var/lib/mysql

volumes:
  datawarehouse:
  magasin-1:
  magasin-2: