services:
  mysql-remote:
    image: mysql:lts
    container_name: mysql-remote
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: cpnv
      MYSQL_PASSWORD: BigPassword
      MYSQL_ROOT_PASSWORD: BigPassword
    volumes:
      - mysql-remote-data:/var/lib/mysql

  mysql-local:
    image: mysql:lts
    container_name: mysql-local
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: cpnv
      MYSQL_PASSWORD: BigPassword
      MYSQL_ROOT_PASSWORD: BigPassword
    volumes:
      - ./config:/etc/mysql/conf.d
      - mysql-local-data:/var/lib/mysql

volumes:
  mysql-remote-data:
  mysql-local-data: