CREATE DATABASE IF NOT EXISTS sql2;
USE sql2;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
)
ENGINE=FEDERATED
CONNECTION='mysql://root:BigPassword@mysql-1:3306/sql2/users';