CREATE DATABASE IF NOT EXISTS datawarehouse;
USE datawarehouse;

CREATE TABLE sales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    shop VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL
)
ENGINE=InnoDB;
